<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>Behrouzan.Results</PackageId>
    <Version>0.1.0</Version>
    <Authors>Behzad Behrouzan</Authors>
    <Description>
      A lightweight, framework-independent Result pattern library for .NET with structured errors, multiple error support, metadata, severity, mapping, binding, matching, and result composition.
    </Description>
    <PackageTags>
      result;result-pattern;error-handling;functional;validation;dotnet
    </PackageTags>

    <RepositoryUrl>https://github.com/behrouzan/dotnet-building-blocks</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <PackageReadmeFile>README.md</PackageReadmeFile>

    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md"
        Pack="true"
        PackagePath="\" />
  </ItemGroup>

</Project>